apiVersion: v1
kind: Service
metadata:
  name: post
  labels:
    app: post
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: post
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: post-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: post
        version: v1
    spec:
      containers:
      - name: post
        image: anthonyamanse/post-v1
        imagePullPolicy: Always
        env:
        - name: MYSQL_DB_USER
          value: 'PLACEHOLDER_DB_USER'
        - name: MYSQL_DB_PASSWORD
          value: 'PLACEHOLDER_DB_PASSWORD'
        - name: MYSQL_DB_HOST
          value: 'PLACEHOLDER_DB_HOST'
        - name: MYSQL_DB_PORT
          value: 'PLACEHOLDER_DB_PORT'
        - name: SLACK_WEBHOOK_URL
          value: 'PLACEHOLDER_SLACK'
        ports:
        - containerPort: 9080
